'use client';
import React,{useMemo,useState} from 'react';
import {Calculator,Layers3,ArrowUpRight,Download,Save,RotateCcw,Info,ChevronRight,HardHat} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Choice,Field,api,download,Tag} from './ui';
import {defaultEstimate,estimateKinds,calculateEstimate,type EstimateInput} from '@/lib/calculator';
import {type Data,yuan,today} from '@/lib/model';
import {toast} from 'sonner';
function quoteCsv(rows:(string|number)[][]){return '\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');}
export default function CalculatorView({data,demo,onSaved,onCreate}:{data:Data;demo:boolean;onSaved:()=>Promise<void>;onCreate:()=>void}){
 const [input,setInput]=useState<EstimateInput>(defaultEstimate),[dialog,setDialog]=useState(false),[projectId,setProjectId]=useState(data.projects[0]?.id||''),[name,setName]=useState(''),[busy,setBusy]=useState(false);
 const line=input.kind==='道路划线',bulk=input.kind==='碎石垫层'||input.kind==='沥青道路';
 const {result,error}=useMemo(()=>{try{return {result:calculateEstimate(input),error:''}}catch(e){return {result:null,error:e instanceof Error?e.message:'请输入有效数值'}}},[input]);
 const set=(key:keyof EstimateInput,value:number|string)=>setInput(p=>({...p,[key]:value}));
 const numeric=(key:keyof EstimateInput,label:string,hint?:string)=><Field label={label} hint={hint}><input aria-label={label} type="number" min="0" step="any" value={Number.isNaN(input[key])?'':input[key]} onChange={e=>set(key,e.target.value===''?NaN:Number(e.target.value))}/></Field>;
 function selectKind(v:string){setInput(p=>({...p,kind:v,price:v==='道路划线'?25:v==='碎石垫层'?85:v==='沥青道路'?450:450,density:v==='沥青道路'?2.4:1.5,factor:1}));}
 function exportQuote(){if(!result)return;download(input.kind+'_报价_'+today()+'.csv',quoteCsv([['筑账工程报价单（估算）'],['工程类型',input.kind],['计算日期',today()],['施工面积（㎡）',result.area],['厚度（cm，非划线）',line?'不适用':input.thickness],['长度（m，划线）',line?input.length:'不适用'],['线宽（cm，划线）',line?input.width:'不适用'],['用料密度（吨/m³）',bulk?input.density:'不适用'],['体积换算系数',bulk?input.factor:'不适用'],['单位耗料量（kg/㎡）',line?input.consumption:'不适用'],['损耗率（%）',input.loss],['预计采购数量（'+result.unit+'）',result.quantity],['材料单价（元/'+result.unit+'）',input.price],['材料费（元）',result.material/100],['人工费（元）',result.labor/100],['机械费（元）',result.machine/100],['运输及其他（元）',result.transport/100],['成本合计（元）',result.cost/100],['成本加价率（%）',input.markup],['加价金额（元）',result.profit/100],['税率（%）',input.tax],['税额（元）',result.tax/100],['报价合计（元）',result.total/100],['每平方米报价（元）',result.perSquare/100],['说明','估算基于所填参数，不代表施工配比、结算工程量或实时市场价。']]));}
 return <><div className="page-heading"><div><h1>算料报价</h1><p>现场填尺寸，材料用量和报价一起算清。</p></div><div className="button-row"><button className="btn" onClick={()=>setInput(defaultEstimate)}><RotateCcw size={16}/>重置参数</button><button className="btn" disabled={!result} onClick={exportQuote}><Download size={16}/>导出报价单</button></div></div>
 <div className="calc-layout"><section className="panel calc-input"><div className="panel-header"><h2><Layers3 size={18}/>施工参数</h2><Tag color="gray">参数可修改</Tag></div><div className="calc-kinds">{estimateKinds.map((v,i)=><button key={v} onClick={()=>selectKind(v)} className={input.kind===v?'selected':''}>{['地坪','道路','碎石','沥青','划线'][i]}</button>)}</div><div className="calc-fields"><Field label="工程类型" wide><Choice className="!w-full" label="选择计算类型" value={input.kind} onChange={selectKind} options={estimateKinds}/></Field>{line?<>{numeric('length','划线总长度（m）')}{numeric('width','线宽（cm）')}{numeric('consumption','单位耗料量（kg/㎡）','按产品说明及涂层厚度填写')}</>:<>{numeric('area','施工面积（㎡）')}{numeric('thickness','成型厚度（cm）')}</>}{bulk&&<>{numeric('density','材料密度（吨/m³）','密度与体积换算口径须一致')}{numeric('factor','体积换算系数','同一口径填 1；避免重复计入压实因素')}</>}{numeric('loss','采购损耗（%）')}<div className="calc-divider">成本与报价</div>{numeric('price',`材料单价（元/${line?'kg':bulk?'吨':'m³'}）`)}{numeric('labor','人工单价（元/㎡）')}{numeric('machine','机械单价（元/㎡）')}{numeric('transport','运输及其他（元）')}{numeric('markup','成本加价率（%）','按成本加价，不等同于毛利率')}{numeric('tax','报价税率（%）','不计税填 0；请自行确定适用税率')}<div className="form-note"><Info size={15} className="inline mr-1"/>初始值仅用于演示，请替换为现场尺寸、供应商单价与材料参数。</div></div></section>
 <div className="calc-output"><section className="calc-result"><div className="calc-result-top"><span>预估报价</span><Calculator size={22}/></div><div className="calc-total"><span>¥</span>{result?yuan(result.total):'—'}</div><p>折合 <b>¥{result?yuan(result.perSquare):'—'}</b> / ㎡</p><div className="calc-quantity"><div><small>预计采购量 · 含损耗</small><strong>{result?result.quantity.toLocaleString('zh-CN',{maximumFractionDigits:3}):'—'} <em>{result?.unit}</em></strong></div><div><small>施工面积</small><strong>{result?result.area.toLocaleString('zh-CN',{maximumFractionDigits:2}):'—'} <em>㎡</em></strong></div></div><button className="btn" disabled={!result} onClick={()=>{if(demo){toast.info('请先进入“我的项目”并新建工程，再保存报价');return}if(!data.projects.length){onCreate();return}setProjectId(data.projects[0].id);setName(input.kind+'报价');setDialog(true)}}><Save size={16}/>保存到工程</button></section>
 <section className="panel calc-breakdown"><div className="panel-header"><h2>费用明细</h2><span className="sensitive-note">人民币 / 元</span></div>{result?[['材料费',result.material],['人工费',result.labor],['机械费',result.machine],['运输及其他',result.transport],['成本合计',result.cost],['加价金额',result.profit],['税额',result.tax]].map(([k,v])=><div className={'cost-row '+(k==='成本合计'?'subtotal':'')} key={k}><span>{k}</span><b>¥{yuan(Number(v))}</b></div>):<div className="error-bar" role="alert">{error}</div>}</section>
 <section className="formula-box"><h3>怎么算出来的？</h3><p>{line?'涂布面积 = 长度 × 线宽 ÷ 100':'成型体积 = 面积 × 厚度 ÷ 100'}</p><p>{line?'采购量 = 涂布面积 × 单位耗料量 × (1 + 损耗率)':bulk?'采购量 = 成型体积 × 体积换算系数 × 密度 × (1 + 损耗率)':'采购量 = 成型体积 × (1 + 损耗率)'}</p><small>报价是预算参考，实际用量需结合施工工艺和现场条件复核。</small></section></div></div>
 {data.estimates.length>0&&<section className="panel mt-6"><div className="panel-header"><h2>已保存的报价</h2></div><Table className="data-table"><TableHeader><TableRow><TableHead>报价名称</TableHead><TableHead>所属工程</TableHead><TableHead>报价总额</TableHead><TableHead>保存日期</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{data.estimates.map(e=><TableRow key={e.id}><TableCell>{e.name}</TableCell><TableCell>{data.projects.find(p=>p.id===e.projectId)?.name}</TableCell><TableCell>¥{yuan(e.result.total)}</TableCell><TableCell>{e.createdAt.slice(0,10)}</TableCell><TableCell><button className="text-btn" onClick={()=>{setInput(e.input);window.scrollTo({top:0,behavior:'smooth'});toast.success('已载入当时的报价参数')}}>查看 / 套用</button></TableCell></TableRow>)}</TableBody></Table></section>}
 <Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="dialog-content"><DialogHeader><DialogTitle>保存报价</DialogTitle><DialogDescription>保存本次参数与结果，后续可以查看和套用。</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('estimates',{projectId,name,input});await onSaved();setDialog(false);toast.success('报价已保存到工程')}catch(e){toast.error(e instanceof Error?e.message:'保存失败')}finally{setBusy(false)}}}><Field label="所属工程" wide><Choice className="!w-full" label="报价所属工程" value={projectId} onChange={setProjectId} options={data.projects.map(p=>({value:p.id,label:p.name}))}/></Field><Field label="报价名称" wide><input required value={name} onChange={e=>setName(e.target.value)}/></Field><div className="form-actions"><button className="btn primary" disabled={busy} type="submit">{busy?'保存中…':'保存报价'}</button></div></form></DialogContent></Dialog>
 </>
}
