'use client';
import React,{useState,useRef} from 'react';
import {OfflineShareForm as ShareForm} from '../offline/panels';
import {Camera,UploadCloud,Loader2,FileCheck2,Info,Copy,Check,Link2} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Choice,Field,api,toCents,moneyInput} from './ui';
import {today,type Data,type Project,type Invoice,type Receivable,remaining,yuan} from '@/lib/model';
export type Modal={type:'project'|'invoice'|'receivable'|'followup'|'upload'|'share';item?:any;projectId?:string;payment?:boolean}|null;
export function FormModal({modal,onClose,data,onSaved}:{modal:Modal;onClose:()=>void;data:Data;onSaved:()=>Promise<void>}){
 return <Dialog open={!!modal} onOpenChange={o=>{if(!o)onClose()}}><DialogContent className="dialog-content"><DialogHeader><DialogTitle>{{project:modal?.item?'编辑工程':'新建工程',invoice:modal?.item?'核对与编辑发票':'录入发票',receivable:modal?.item?'编辑回款计划':'添加回款计划',followup:modal?.payment?'登记实际收款':'记录催收跟进',upload:'上传项目资料',share:'共享项目'}[modal?.type||'project']}</DialogTitle><DialogDescription>{{project:'项目、票据和资料都归在这里。',invoice:'识别后请核对金额与票号，确认后再入账。',receivable:'按合同约定填写应收金额与到期日期。',followup:modal?.payment?'只登记已经到账的款项，支持分次收回。':'留下沟通结果，方便下次接着跟。',upload:'原件会保存在所选工程，可随项目打包下载。',share:'导出指定工程的资料包，供会计或老板查看。'}[modal?.type||'project']}</DialogDescription></DialogHeader>{modal&&<FormBody key={modal.type+(modal.item?.id||'')} modal={modal} data={data} close={onClose} saved={onSaved}/>}</DialogContent></Dialog>
}
function FormBody({modal,data,close,saved}:{modal:NonNullable<Modal>;data:Data;close:()=>void;saved:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(task:()=>Promise<unknown>){setBusy(true);setError('');try{await task();await saved();toast.success('已保存');close()}catch(e){setError(e instanceof Error?e.message:'保存失败')}finally{setBusy(false)}}
 const props={data,modal,busy,save};
 return <>{error&&<div className="error-bar" role="alert">{error}</div>}{modal.type==='project'?<ProjectForm {...props}/>:modal.type==='invoice'?<InvoiceForm {...props}/>:modal.type==='receivable'?<ReceivableForm {...props}/>:modal.type==='followup'?<FollowupForm {...props}/>:modal.type==='upload'?<UploadForm {...props}/>:<ShareForm data={data} modal={modal} saved={saved}/>}</>
}
type Props={data:Data;modal:NonNullable<Modal>;busy:boolean;save:(task:()=>Promise<unknown>)=>Promise<void>};
function ProjectChoice({data,value,set}:{data:Data;value:string;set:(s:string)=>void}){return <Field label="所属工程 *" wide><Choice className="!w-full" label="所属工程" value={value} onChange={set} options={data.projects.map(p=>({value:p.id,label:p.name}))}/></Field>}
function Submit({busy,label='保存'}:{busy:boolean;label?:string}){return <div className="form-actions"><button disabled={busy} className="btn primary" type="submit">{busy&&<Loader2 className="spin" size={16}/>} {busy?'正在保存…':label}</button></div>}
function ProjectForm({modal,save,busy}:Props){const old=modal.item as Project|undefined;const [status,setStatus]=useState(old?.status||'施工中'),[category,setCategory]=useState(old?.category||'道路工程');return <form className="dialog-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>api('projects'+(old?'/'+old.id:''),{name:f.get('name'),code:f.get('code'),client:f.get('client'),manager:f.get('manager'),phone:f.get('phone'),location:f.get('location'),category,status,contract:toCents(String(f.get('contract'))),invoiceTarget:toCents(String(f.get('invoiceTarget'))),invoiceDue:f.get('invoiceDue'),completedAt:f.get('completedAt'),note:f.get('note')},old?'PATCH':'POST'))}}>
 <Field label="工程名称 *" wide><input name="name" required maxLength={100} placeholder="例如：滨江路人行道改造" defaultValue={old?.name}/></Field>
 <Field label="工程编号"><input name="code" placeholder="如 SZ-2026-001" defaultValue={old?.code}/></Field><Field label="工程类型"><Choice value={category} onChange={setCategory} label="工程类型" className="!w-full" options={['道路工程','地坪工程','碎石工程','划线工程','排水工程','园林工程','照明工程','配套工程','其他工程']}/></Field>
 <Field label="甲方 / 客户" wide><input name="client" placeholder="填写建设单位或客户名称" defaultValue={old?.client}/></Field>
 <Field label="负责人"><input name="manager" defaultValue={old?.manager}/></Field><Field label="联系电话"><input name="phone" type="tel" defaultValue={old?.phone}/></Field>
 <Field label="工程地点"><input name="location" defaultValue={old?.location}/></Field><Field label="工程状态"><Choice label="工程状态" className="!w-full" value={status} onChange={setStatus} options={['施工中','已竣工','质保期','已归档']}/></Field>
 <Field label="合同金额（元）"><input name="contract" type="number" min="0" step="0.01" required defaultValue={moneyInput(old?.contract||0)}/></Field><Field label="应收成本票金额（元）" hint="按实际采购、分包等业务确定"><input name="invoiceTarget" type="number" min="0" step="0.01" required defaultValue={moneyInput(old?.invoiceTarget||0)}/></Field>
 <Field label="应收票截止日"><input name="invoiceDue" type="date" defaultValue={old?.invoiceDue}/></Field><Field label="竣工日期"><input name="completedAt" type="date" defaultValue={old?.completedAt}/></Field>
 <Field label="备注" wide><textarea name="note" maxLength={500} defaultValue={old?.note}/></Field><Submit busy={busy}/></form>}
function InvoiceForm({data,modal,save,busy}:Props){const old=modal.item as Invoice|undefined;const [projectId,setProjectId]=useState(old?.projectId||modal.projectId||data.projects[0]?.id||''),[category,setCategory]=useState(old?.category||'材料费'),[status,setStatus]=useState(old?.status||'待核对'),[file,setFile]=useState<File|null>(null),[reading,setReading]=useState(false),[ocrNote,setOcrNote]=useState(''),[fields,setFields]=useState({number:old?.number||'',code:old?.code||'',seller:old?.seller||'',buyer:old?.buyer||'',amount:old?moneyInput(old.amount):'',tax:old?moneyInput(old.tax):'0',date:old?.date||today()});
 const set=(k:string,v:string)=>setFields(p=>({...p,[k]:v}));const fileId=useRef(old?.fileId||'');const uploadProject=useRef(projectId);
 async function read(){if(!file)return;setReading(true);setOcrNote('');try{const form=new FormData();form.append('file',file);const r=await api('ocr',form);setFields({number:r.number,code:r.code,seller:r.seller,buyer:r.buyer,amount:r.amount?moneyInput(r.amount):'',tax:moneyInput(r.tax||0),date:r.date||today()});setStatus('待核对');setOcrNote('识别完成，请逐项核对后保存。')}catch(e){setOcrNote(e instanceof Error?e.message:'识别失败')}finally{setReading(false)}}
 return <form className="dialog-form" onSubmit={e=>{e.preventDefault();void save(async()=>{if(!projectId)throw Error('请先新建工程');if(file&&(!fileId.current||uploadProject.current!==projectId)){const form=new FormData();form.append('file',file);form.append('projectId',projectId);form.append('category','发票原件');const r=await api('upload',form);fileId.current=r.id;uploadProject.current=projectId;}return api('invoices'+(old?'/'+old.id:''),{...fields,projectId,category,status,amount:toCents(fields.amount),tax:toCents(fields.tax),fileId:fileId.current},old?'PATCH':'POST')})}}>
 <ProjectChoice data={data} value={projectId} set={v=>{setProjectId(v);if(!file)fileId.current=''}}/>
 <div className="field wide"><label className="upload-area"><Camera size={29}/><span>{file?file.name:old?.fileId?'已有发票原件，可选择替换':'拍照或选择发票图片'}</span><small>图片 / PDF / OFD · 原件不超过 10MB</small><input aria-label="选择发票文件" type="file" accept="image/jpeg,image/png,image/webp,application/pdf,.ofd" onChange={e=>{setFile(e.target.files?.[0]||null);fileId.current='';setOcrNote('')}}/></label>{file&&<button type="button" className="btn" disabled={reading||!data.services?.ocr} onClick={read}>{reading?<Loader2 size={16} className="spin"/>:<FileCheck2 size={16}/>} {reading?'正在识别…':'识别并填入'}</button>}{!data.services?.ocr&&<small>离线版采用手动录入，可上传原件并核对填写。</small>}{ocrNote&&<div className="form-note" role="status">{ocrNote}</div>}</div>
 <Field label="发票号码 *"><input value={fields.number} required inputMode="numeric" pattern="[0-9]{8,30}" onChange={e=>set('number',e.target.value)}/></Field><Field label="发票代码" hint="数电票可留空"><input value={fields.code} inputMode="numeric" onChange={e=>set('code',e.target.value)}/></Field>
 <Field label="销售方 *" wide><input value={fields.seller} required onChange={e=>set('seller',e.target.value)}/></Field><Field label="购买方" wide><input value={fields.buyer} onChange={e=>set('buyer',e.target.value)}/></Field>
 <Field label="价税合计（元）*"><input type="number" min="0.01" step="0.01" required value={fields.amount} onChange={e=>set('amount',e.target.value)}/></Field><Field label="税额（元）"><input type="number" min="0" step="0.01" required value={fields.tax} onChange={e=>set('tax',e.target.value)}/></Field>
 <Field label="开票日期 *"><input type="date" value={fields.date} required onChange={e=>set('date',e.target.value)}/></Field><Field label="费用分类"><Choice className="!w-full" label="费用分类" value={category} onChange={setCategory} options={['材料费','机械费','人工费','分包费','运输费','其他费用']}/></Field>
 <Field label="核对状态"><Choice className="!w-full" label="核对状态" value={status} onChange={setStatus} options={['待核对','已核对','已作废']}/></Field><p className="sensitive-note">只有“已核对”的发票计入已收票金额。核对状态不代表税务真伪核验。</p><Submit busy={busy} label="保存发票"/>
 </form>}
function ReceivableForm({data,modal,save,busy}:Props){const old=modal.item as Receivable|undefined;const [projectId,setProjectId]=useState(old?.projectId||modal.projectId||data.projects[0]?.id||''),[type,setType]=useState(old?.type||'质保金');return <form className="dialog-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>api('receivables'+(old?'/'+old.id:''),{projectId,type,amount:toCents(String(f.get('amount'))),due:f.get('due'),reminderDays:Number(f.get('reminderDays')),contact:f.get('contact'),note:f.get('note')},old?'PATCH':'POST'))}}>
 <ProjectChoice data={data} value={projectId} set={old?()=>{}:setProjectId}/><Field label="款项类型"><Choice className="!w-full" label="款项类型" value={type} onChange={setType} options={['质保金','尾款']}/></Field><Field label="应收总金额（元）*"><input type="number" name="amount" min="0.01" step="0.01" required defaultValue={old?moneyInput(old.amount):''}/></Field>
 <Field label="合同约定到期日 *"><input type="date" name="due" required defaultValue={old?.due}/></Field><Field label="提前多少天预警"><input type="number" name="reminderDays" min="1" max="730" required defaultValue={old?.reminderDays||data.settings.reminderDays}/></Field>
 <Field label="甲方联系人" wide><input name="contact" defaultValue={old?.contact} placeholder="姓名 / 电话"/></Field><Field label="付款条件与备注" wide><textarea name="note" maxLength={500} defaultValue={old?.note} placeholder="例如：验收合格满两年，提交保修期满证明后支付"/></Field>
 <div className="form-note">到期日由合同确定，不会按统一质保年限自动推算。首页和待办会按所填日期预警。</div><Submit busy={busy}/></form>}
function FollowupForm({data,modal,save,busy}:Props){const r=modal.item as Receivable;const [method,setMethod]=useState(modal.payment?'收款':'电话'),[requestId]=useState(()=>crypto.randomUUID());return <form className="dialog-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>api('followups',{requestId,projectId:r.projectId,receivableId:r.id,date:f.get('date'),method,content:f.get('content'),nextDate:f.get('nextDate')||'',amount:modal.payment?toCents(String(f.get('amount'))):0}))}}>
 <div className="form-note">{data.projects.find(p=>p.id===r.projectId)?.name} · {r.type}<br/>当前待收 <b>¥{yuan(remaining(r))}</b></div>
 <Field label={modal.payment?'收款日期 *':'沟通日期 *'}><input name="date" type="date" defaultValue={today()} max={today()} required/></Field>{modal.payment?<Field label="本次到账（元）*"><input name="amount" type="number" required min="0.01" step="0.01" max={remaining(r)/100} placeholder="填写实际到账金额"/></Field>:<Field label="沟通方式"><Choice className="!w-full" label="沟通方式" value={method} onChange={setMethod} options={['电话','微信','当面','邮件','其他']}/></Field>}
 <Field wide label={modal.payment?'收款说明 *':'跟进内容 *'}><textarea name="content" required maxLength={500} placeholder={modal.payment?'如：收到甲方转账，尾款第一笔':'记录对方答复、已提交资料或约定的付款时间'}/></Field>{!modal.payment&&<Field label="下次跟进日期" wide><input type="date" name="nextDate" min={today()}/></Field>}<Submit busy={busy} label={modal.payment?'确认登记收款':'保存跟进'}/></form>}
function UploadForm({data,modal,save,busy}:Props){const[projectId,setProjectId]=useState(modal.projectId||data.projects[0]?.id||''),[category,setCategory]=useState('合同协议'),[files,setFiles]=useState<File[]>([]);return <form className="dialog-form" onSubmit={e=>{e.preventDefault();void save(async()=>{if(!files.length)throw Error('请选择资料文件');for(const file of files){const f=new FormData();f.append('file',file);f.append('projectId',projectId);f.append('category',category);await api('upload',f);setFiles(p=>p.filter(x=>x!==file));}setFiles([]);})}}><ProjectChoice data={data} value={projectId} set={setProjectId}/><Field label="资料分类" wide><Choice className="!w-full" label="资料分类" value={category} onChange={setCategory} options={['合同协议','发票原件','竣工资料','现场照片','其他资料']}/></Field><div className="field wide"><label className="upload-area"><UploadCloud size={32}/><span>选择项目资料</span><small>每个文件不超过 10MB</small><input type="file" multiple aria-label="选择项目资料" accept=".pdf,.png,.jpg,.jpeg,.webp,.doc,.docx,.xls,.xlsx,.txt,.zip,.ofd" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>{files.map((f,i)=><small key={i}>{f.name} · {(f.size/1024/1024).toFixed(2)} MB</small>)}</div><Submit busy={busy} label="上传并归档"/></form>}
