import fs from 'node:fs';
import path from 'node:path';
const out=path.resolve('docs/index.html');
const script=fs.readFileSync('build/app.iife.js','utf8').replace(/<\/script/gi,'<\\/script');
const css=fs.readFileSync('build/app.css','utf8');
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'"><title>筑账 · 免服务器离线版</title><style>${css}</style></head><body><div id="root"><p style="padding:32px;font-family:sans-serif">正在打开本地账本…请使用电脑 Edge 或 Chrome 普通窗口。</p></div><noscript>请启用 JavaScript 后打开此离线账本。</noscript><script>${script}</script></body></html>`;
const installHead='<meta name="theme-color" content="#176b59"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="筑账"><link rel="manifest" href="./manifest.webmanifest"><link rel="apple-touch-icon" href="./icons/icon-192.png">';
const installScript='<script>if(location.protocol==="https:"&&"serviceWorker" in navigator){addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));}</script>';
const webHtml=html.replace("connect-src 'none';","connect-src 'self'; worker-src 'self'; manifest-src 'self';").replace('img-src data: blob:;',"img-src 'self' data: blob:;").replace('</head>',installHead+'</head>').replace('</body>',installScript+'</body>');
fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,webHtml);fs.writeFileSync('build/offline.html',html);fs.writeFileSync(path.join(path.dirname(out),'.nojekyll'),'');console.log(out+' ('+Buffer.byteLength(webHtml)+' bytes)');
