import {snapshot,replaceBook,saveBlob} from './storage';
import {validateBackup} from './mutations';
import {zipStream,csv,type ZipEntry} from '../server/zip';
import {today,remaining,gap,yuan,type Data} from '../lib/model';
const enc=new TextEncoder();const safe=(v:string)=>v.replace(/[\\/<>:"|?*\x00-\x1f]/g,'_').replace(/^\.+/,'').slice(0,100)||'资料';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const textEntry=(name:string,text:string):ZipEntry=>({name,load:async()=>enc.encode(text)});
export async function exportBackup(){const {data,files}=await snapshot();const createdAt=new Date().toISOString();const entries:ZipEntry[]=[textEntry('账本.json',JSON.stringify({format:'zhuzhang-offline',version:1,createdAt,data}))];for(const doc of data.documents){const file=files.get(doc.id);if(!file)throw Error('存在缺失原件，无法生成完整备份');entries.push({name:'files/'+doc.id,load:async()=>file.stream()})}await saveBlob(await new Response(zipStream(entries)).blob(),'筑账完整备份_'+today()+'.zip');return createdAt}
const crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}const crc32=(bytes:Uint8Array)=>{let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0};
export function readBackupZip(buffer:ArrayBuffer){const bytes=new Uint8Array(buffer),view=new DataView(buffer);let end=-1;for(let p=bytes.length-22;p>=Math.max(0,bytes.length-65557);p--){if(view.getUint32(p,true)===0x06054b50&&p+22+view.getUint16(p+20,true)===bytes.length){end=p;break}}if(end<0)throw Error('备份 ZIP 已损坏');const count=view.getUint16(end+10,true),central=view.getUint32(end+16,true),centralSize=view.getUint32(end+12,true);if(count>50001||central+centralSize>end||view.getUint16(end+4,true)!==0)throw Error('备份结构不受支持');const files=new Map<string,Uint8Array>();let p=central;for(let i=0;i<count;i++){if(p+46>end||view.getUint32(p,true)!==0x02014b50)throw Error('备份目录已损坏');const compression=view.getUint16(p+10,true),crc=view.getUint32(p+16,true),size=view.getUint32(p+24,true),packed=view.getUint32(p+20,true),nameSize=view.getUint16(p+28,true),extra=view.getUint16(p+30,true),comment=view.getUint16(p+32,true),offset=view.getUint32(p+42,true);if(compression!==0||size!==packed||p+46+nameSize+extra+comment>end||offset+30>central||view.getUint32(offset,true)!==0x04034b50)throw Error('请导入由筑账离线版直接导出的完整备份 ZIP，不要重新压缩');const name=new TextDecoder('utf-8',{fatal:true}).decode(bytes.subarray(p+46,p+46+nameSize));const start=offset+30+view.getUint16(offset+26,true)+view.getUint16(offset+28,true);if(start+size>central||files.has(name))throw Error('备份文件结构异常');const data=bytes.slice(start,start+size);if(crc32(data)!==crc)throw Error('备份校验失败，文件可能损坏');files.set(name,data);p+=46+nameSize+extra+comment}if(p!==central+centralSize)throw Error('备份目录长度异常');return files}
export async function prepareRestore(file:File){if(file.size>250*1024*1024)throw Error('备份文件不能超过 250MB');const entries=readBackupZip(await file.arrayBuffer());const manifest=entries.get('账本.json');if(!manifest)throw Error('这是工程资料包，不是可恢复的完整备份');let raw:any;try{raw=JSON.parse(new TextDecoder().decode(manifest))}catch{throw Error('备份账本内容无法读取')}const data=validateBackup(raw),files=new Map<string,Blob>();if(entries.size!==data.documents.length+1)throw Error('备份原件数量不一致');for(const doc of data.documents){const value=entries.get('files/'+doc.id);if(!value||value.byteLength!==doc.size)throw Error('备份资料原件不完整');files.set(doc.id,new Blob([value.slice().buffer as ArrayBuffer],{type:doc.mime}))}return{data,files,createdAt:String(raw.createdAt||'')}}
export async function restoreBackup(prepared:Awaited<ReturnType<typeof prepareRestore>>){await replaceBook(prepared.data,prepared.files)}
export async function exportProject(projectId:string){const {data,files}=await snapshot(),p=data.projects.find(x=>x.id===projectId);if(!p)throw Error('工程不存在');const invoices=data.invoices.filter(x=>x.projectId===p.id),receipts=data.receivables.filter(x=>x.projectId===p.id),followups=data.followups.filter(x=>x.projectId===p.id),docs=data.documents.filter(x=>x.projectId===p.id),estimates=data.estimates.filter(x=>x.projectId===p.id);const entries:ZipEntry[]=[];const rows=(items:unknown[][])=>items.map(row=>'<tr>'+row.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('');const docPath=(d:any)=>'资料原件/'+safe(d.category)+'/'+d.id.slice(0,8)+'_'+safe(d.name);
 const html='<!doctype html><html lang="zh-CN"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'"><title>'+esc(p.name)+' · 工程资料</title><style>body{max-width:1000px;margin:32px auto;padding:0 22px;font:16px/1.8 Arial,Microsoft YaHei,sans-serif;color:#263c34}h1{color:#176b59}h2{font-size:20px;margin-top:32px}table{border-collapse:collapse;width:100%;font-size:14px}th,td{border:1px solid #dce6df;padding:10px;text-align:left;overflow-wrap:anywhere}th{background:#f0f6f2}.scroll{overflow:auto}p{color:#66796d}a{color:#176b59}@media print{body{margin:0}a{color:black}}</style><h1>'+esc(p.name)+'</h1><p>筑账 · 导出时点 '+esc(new Date().toLocaleString('zh-CN'))+' · 只读资料快照</p><p>甲方：'+esc(p.client||'未填')+'<br>负责人：'+esc(p.manager||'未填')+'<br>合同额：¥'+yuan(p.contract)+'　成本票缺口：¥'+yuan(gap(data,p))+'</p><h2>质保金与尾款</h2><div class="scroll"><table><tr><th>款项</th><th>到期日</th><th>应收元</th><th>已收元</th><th>待收元</th></tr>'+rows(receipts.map(r=>[r.type,r.due,yuan(r.amount),yuan(r.received),yuan(remaining(r))]))+'</table></div><h2>发票台账</h2><div class="scroll"><table><tr><th>票号</th><th>销售方</th><th>日期</th><th>价税合计元</th><th>状态</th></tr>'+rows(invoices.map(i=>[i.number,i.seller,i.date,yuan(i.amount),i.status]))+'</table></div><h2>催收记录</h2><div class="scroll"><table><tr><th>日期</th><th>方式</th><th>记录</th><th>本次到账元</th><th>下次跟进</th></tr>'+rows(followups.map(f=>[f.date,f.method,f.content,yuan(f.amount),f.nextDate]))+'</table></div><h2>资料原件</h2><ul>'+docs.map(d=>'<li><a href="'+docPath(d).split('/').map(encodeURIComponent).join('/')+'">'+esc(d.name)+'</a>（'+esc(d.category)+'）</li>').join('')+'</ul><p>本文件不会自动更新；更改记录后需重新导出。原件请先解压整个 ZIP 再点击查看。可用浏览器打印功能另存为 PDF。</p></html>';
 entries.push(textEntry('打开查看工程.html',html),textEntry('项目概况.json',JSON.stringify(p,null,2)),textEntry('发票台账.csv',csv([['发票号码','销售方','开票日期','价税合计元','税额元','分类','状态'],...invoices.map(i=>[i.number,i.seller,i.date,i.amount/100,i.tax/100,i.category,i.status])])),textEntry('回款台账.csv',csv([['款项','到期日','应收元','已收元','待收元'],...receipts.map(r=>[r.type,r.due,r.amount/100,r.received/100,remaining(r)/100])])),textEntry('催收记录.csv',csv([['日期','方式','内容','到账元','下次跟进'],...followups.map(f=>[f.date,f.method,f.content,f.amount/100,f.nextDate])])),textEntry('算料报价.json',JSON.stringify(estimates,null,2)));
 for(const d of docs){const file=files.get(d.id);if(!file)throw Error('部分原件缺失，请先恢复完整备份');entries.push({name:docPath(d),load:async()=>file.stream()})}await saveBlob(await new Response(zipStream(entries)).blob(),safe(p.name)+'_工程资料包_'+today()+'.zip')}
function fold(s:string){let line='',out='';for(const char of s){if(enc.encode(line+char).length>73){out+=line+'\r\n';line=' '}line+=char}return out+line}
export function calendarText(data:Data){const clean=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const rows=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Zhuzhang//Offline 1.0//ZH','CALSCALE:GREGORIAN','METHOD:PUBLISH'];let count=0;for(const r of data.receivables.filter(r=>remaining(r)>0&&r.due>=today())){const p=data.projects.find(p=>p.id===r.projectId);const end=new Date(r.due+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+1);rows.push('BEGIN:VEVENT','UID:'+r.id+'@zhuzhang-offline','DTSTAMP:'+stamp,'DTSTART;VALUE=DATE:'+r.due.replace(/-/g,''),'DTEND;VALUE=DATE:'+end.toISOString().slice(0,10).replace(/-/g,''),'SUMMARY:'+clean((p?.name||'工程')+' · '+r.type+'到期'),'DESCRIPTION:'+clean('待收 ¥'+yuan(remaining(r))+'；联系人：'+r.contact+'；'+r.note+'。金额为导出时点，请以账本为准。'));for(const days of new Set([r.reminderDays,1]))rows.push('BEGIN:VALARM','TRIGGER:-P'+days+'D','ACTION:DISPLAY','DESCRIPTION:'+clean((p?.name||'工程')+' '+r.type+'即将到期'),'END:VALARM');rows.push('END:VEVENT');count++}rows.push('END:VCALENDAR');return{text:rows.map(fold).join('\r\n')+'\r\n',count}}
export async function exportCalendar(){const {data}=await snapshot(),result=calendarText(data);if(!result.count)throw Error('没有今天或之后到期的未结清款项，请先添加回款计划');await saveBlob(new Blob([result.text],{type:'text/calendar;charset=utf-8'}),'筑账到期提醒_'+today()+'.ics');return result.count}
