import {emptyData,type Data} from '../lib/model';
import {applyMutation} from './mutations';
import {saveNative} from './native-export';
const STORES=['state','files'];const LIMIT=200*1024*1024;
let opening:Promise<IDBDatabase>|undefined;
function db(){if(!opening)opening=new Promise((resolve,reject)=>{try{const r=indexedDB.open('zhuzhang-offline-v1',1);r.onupgradeneeded=()=>{for(const name of STORES)if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('此浏览器无法保存本地账本，请用电脑 Edge 或 Chrome 普通窗口打开。'))}catch{reject(Error('本地存储不可用，请用电脑 Edge 或 Chrome 普通窗口打开。'))}});return opening}
const fresh=()=>({...structuredClone(emptyData),settings:{...emptyData.settings,company:'我的离线账本'}});
const view=(d:Data)=>({...d,authenticated:true,services:{ocr:false,wecom:false,email:false,scheduled:false}});
export async function getData(){const connection=await db();return new Promise<Data>((resolve,reject)=>{const t=connection.transaction('state'),r=t.objectStore('state').get('book');r.onsuccess=()=>resolve(view(r.result||fresh()));r.onerror=()=>reject(r.error)})}
export async function getFile(id:string){const connection=await db();return new Promise<Blob>((resolve,reject)=>{const t=connection.transaction('files'),r=t.objectStore('files').get(id);r.onsuccess=()=>r.result?resolve(r.result):reject(Error('原件不存在，请从完整备份恢复'));r.onerror=()=>reject(r.error)})}
export async function snapshot(){const connection=await db();return new Promise<{data:Data;files:Map<string,Blob>}>((resolve,reject)=>{const t=connection.transaction(STORES),r=t.objectStore('state').get('book'),files=new Map<string,Blob>();let data:Data=fresh();r.onsuccess=()=>{data=r.result||fresh()};const cursor=t.objectStore('files').openCursor();cursor.onsuccess=()=>{const c=cursor.result;if(c){files.set(String(c.key),c.value);c.continue()}};t.oncomplete=()=>resolve({data,files});t.onerror=()=>reject(t.error)})}
async function change(task:(data:Data,t:IDBTransaction)=>any){const connection=await db();return new Promise<any>((resolve,reject)=>{const t=connection.transaction(STORES,'readwrite'),state=t.objectStore('state'),r=state.get('book');let result:any,error:unknown;r.onsuccess=()=>{try{const d:Data=r.result||fresh();result=task(d,t);state.put(d,'book')}catch(e){error=e;t.abort()}};t.oncomplete=()=>{window.dispatchEvent(new Event('zhuzhang-data'));resolve(result)};t.onabort=()=>reject(error||Error(t.error?.name==='QuotaExceededError'?'浏览器存储空间不足，保存未完成。请先导出备份。':'保存未完成，请重试'));t.onerror=()=>{}})}
export async function localApi(path:string,body?:any,method='POST'){
 try{
 if(path==='data'&&body===undefined)return await getData();
 if(path==='ocr')throw Error('离线版不连接发票识别服务，请上传原件并手动填写。');
 if(path==='upload'){const file=body.get('file'),projectId=String(body.get('projectId')||''),category=String(body.get('category')||'其他资料');if(!(file instanceof File)||file.size===0||file.size>10*1024*1024)throw Error('单个非空文件不能超过 10MB');if(!/\.(pdf|png|jpe?g|webp|docx?|xlsx?|txt|zip|ofd)$/i.test(file.name))throw Error('支持 PDF、图片、Word、Excel、TXT、ZIP、OFD');if(!['合同协议','发票原件','竣工资料','现场照片','其他资料'].includes(category))throw Error('资料分类无效');return await change((d,t)=>{if(!d.projects.some(p=>p.id===projectId))throw Error('请选择已保存的工程');if(d.documents.reduce((s,f)=>s+f.size,0)+file.size>LIMIT)throw Error('离线版原件总量上限 200MB，请先导出工程包并改用服务器版存放更多原件');const doc={id:crypto.randomUUID(),projectId,name:file.name,category,size:file.size,mime:file.type||'application/octet-stream',key:'',createdAt:new Date().toISOString()};doc.key='files/'+doc.id;t.objectStore('files').put(file,doc.id);d.documents.unshift(doc);return doc})}
 return await change(d=>applyMutation(d,path,body,method));
 }catch(e:any){if(e?.issues)throw Error(e.issues.map((x:any)=>x.message).join('；'));throw e}
}
export async function replaceBook(data:Data,files:Map<string,Blob>){if(data.documents.reduce((s,f)=>s+f.size,0)>LIMIT)throw Error('备份原件超过离线版 200MB 上限');return change((d,t)=>{for(const key of Object.keys(d))delete(d as any)[key];Object.assign(d,data);const store=t.objectStore('files');store.clear();for(const doc of data.documents){const file=files.get(doc.id);if(!file||file.size!==doc.size)throw Error('备份中的资料原件不完整');store.put(file,doc.id)}return true})}
export async function saveBlob(blob:Blob,name:string){if(await saveNative(blob,name))return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
export async function downloadFile(id:string){const d=await getData(),doc=d.documents.find(f=>f.id===id);if(!doc)throw Error('资料不存在');await saveBlob(await getFile(id),doc.name)}
