plugins { id 'com.android.application' }
android {
    namespace 'io.github.fuzzylogic112.zhuzhang'
    compileSdk 35
    defaultConfig {
        applicationId 'io.github.fuzzylogic112.zhuzhang'
        minSdk 26
        targetSdk 35
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        versionCode 120
        versionName '1.2.0'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes { release { minifyEnabled false } }
}
dependencies {
    implementation 'androidx.webkit:webkit:1.14.0'
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.exifinterface:exifinterface:1.4.1'
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
}
